apiVersion: apps/v1
kind: Deployment

metadata:
  name: hiring-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hiring-app

  template:
    metadata:
      labels:
        app: hiring-app

    spec:
      containers:
      - name: hiring-app
        image: vigneshadlagatta1/hiring-app:v1

        ports:
        - containerPort: 8080
